package dev.olek.lmclient.data.repositories

import dev.olek.lmclient.data.local.AttachmentStore
import dev.olek.lmclient.data.models.AttachmentContentReference
import io.github.vinceglb.filekit.BookmarkData
import io.github.vinceglb.filekit.PlatformFile
import io.github.vinceglb.filekit.mimeType
import io.github.vinceglb.filekit.readBytes
import org.koin.core.annotation.Single
import kotlin.io.encoding.Base64

/**
 * Repository for managing file attachments in chat messages.
 *
 * Handles storage and retrieval of attachments (images, videos, audio, files)
 * that can be attached to user or assistant messages. All attachments are stored
 * as Base64-encoded content in disc cache.
 *
 * This repository was introduced to optimize DB operations by avoiding storing Base64 content
 * directly in the database. Instead, it uses short [AttachmentContentReference] pointers to content
 * stored in disc cache.
 */
interface AttachmentsRepository {

    /**
     * Processes a user-selected file for attachment to a message.
     *
     * Reads the file from the given URI, encodes it to Base64, and stores
     * the content in disc cache for later retrieval.
     *
     * @param attachmentFile abstracted away platform-specific file.
     * @return [AttachmentContentReference] pointing to the stored attachment.
     */
    suspend fun processUserAttachment(
        attachmentFile: PlatformFile,
    ): AttachmentContentReference

    /**
     * Processes an assistant-generated attachment for storage.
     *
     * Stores the already Base64-encoded content in disc cache. Used for
     * attachments generated by the AI assistant (e.g., generated images).
     *
     * @param base64 Base64-encoded content of the attachment.
     * @param mimeType MIME type of the content.
     * @return [AttachmentContentReference] pointing to the stored attachment.
     */
    suspend fun processAssistantAttachment(
        base64: String,
        mimeType: String,
    ): AttachmentContentReference

    /**
     * Retrieves the Base64-encoded content of a stored attachment.
     *
     * @param reference Reference to the attachment obtained from [processUserAttachment]
     *                  or [processAssistantAttachment].
     * @return [AttachmentContent] containing the Base64-encoded data.
     */
    suspend fun getAttachmentContent(reference: AttachmentContentReference): AttachmentContent

    /**
     * Deletes a stored attachment from cache.
     *
     * @param reference Reference to the attachment to delete.
     */
    suspend fun deleteAttachment(reference: AttachmentContentReference)

    /**
     * Wrapper for attachment content data.
     *
     * @property base64 Base64-encoded content of the attachment.
     */
    data class AttachmentContent(val base64: String)
}

@Single(binds = [AttachmentsRepository::class])
internal class AttachmentsRepositoryImpl(
    private val attachmentStore: AttachmentStore,
) : AttachmentsRepository {
    override suspend fun processUserAttachment(
        attachmentFile: PlatformFile,
    ): AttachmentContentReference {
        val base64 = Base64.encode(attachmentFile.readBytes())
        val mimeType = attachmentFile.mimeType().toString()
        val bookmarkData = attachmentStore.saveAttachment(base64, mimeType)
        return AttachmentContentReference.LocalFile(pathBytes = bookmarkData.bytes)
    }

    override suspend fun processAssistantAttachment(
        base64: String,
        mimeType: String,
    ): AttachmentContentReference {
        val bookmarkData = attachmentStore.saveAttachment(base64, mimeType)
        return AttachmentContentReference.LocalFile(pathBytes = bookmarkData.bytes)
    }

    override suspend fun getAttachmentContent(
        reference: AttachmentContentReference,
    ): AttachmentsRepository.AttachmentContent {
        require(reference is AttachmentContentReference.LocalFile) {
            "Only local files are supported for now"
        }
        val base64 = attachmentStore.getAttachmentContent(
            bookmarkData = BookmarkData(reference.pathBytes),
        )
        return AttachmentsRepository.AttachmentContent(base64)
    }

    override suspend fun deleteAttachment(
        reference: AttachmentContentReference,
    ) {
        require(reference is AttachmentContentReference.LocalFile) {
            "Only local files are supported for now"
        }
        attachmentStore.removeAttachment(BookmarkData(reference.pathBytes))
    }
}
