package dev.olek.lmclient.data.repositories

import dev.olek.lmclient.data.local.AttachmentStore
import dev.olek.lmclient.data.models.AttachmentReference
import kotlin.io.encoding.Base64

/**
 * Repository for managing file attachments in chat messages.
 *
 * Handles storage and retrieval of attachments (images, videos, audio, files)
 * that can be attached to user or assistant messages. All attachments are stored
 * as Base64-encoded content in disc cache.
 *
 * This repository was introduced to optimize DB operations by avoiding storing Base64 content
 * directly in the database. Instead, it uses short [AttachmentReference] pointers to content
 * stored in disc cache.
 */
interface AttachmentsRepository {

    /**
     * Processes a user-selected file for attachment to a message.
     *
     * Reads the file from the given URI, encodes it to Base64, and stores
     * the content in disc cache for later retrieval.
     *
     * @param fileUri Platform-specific URI pointing to the user's file.
     * @param mimeType MIME type of the file (e.g., "image/png", "application/pdf").
     * @return [AttachmentReference] pointing to the stored attachment.
     */
    suspend fun processUserAttachment(
        fileUri: String,
        mimeType: String,
    ): AttachmentReference

    /**
     * Processes an assistant-generated attachment for storage.
     *
     * Stores the already Base64-encoded content in disc cache. Used for
     * attachments generated by the AI assistant (e.g., generated images).
     *
     * @param base64 Base64-encoded content of the attachment.
     * @param mimeType MIME type of the content.
     * @return [AttachmentReference] pointing to the stored attachment.
     */
    suspend fun processAssistantAttachment(
        base64: String,
        mimeType: String,
    ): AttachmentReference

    /**
     * Retrieves the Base64-encoded content of a stored attachment.
     *
     * @param reference Reference to the attachment obtained from [processUserAttachment]
     *                  or [processAssistantAttachment].
     * @return [AttachmentContent] containing the Base64-encoded data.
     */
    suspend fun getAttachmentContent(reference: AttachmentReference): AttachmentContent

    /**
     * Deletes a stored attachment from cache.
     *
     * @param reference Reference to the attachment to delete.
     */
    suspend fun deleteAttachment(reference: AttachmentReference)

    /**
     * Wrapper for attachment content data.
     *
     * @property base64 Base64-encoded content of the attachment.
     */
    value class AttachmentContent(val base64: String)
}

internal class AttachmentsRepositoryImpl(
    private val attachmentStore: AttachmentStore,
) : AttachmentsRepository {
    override suspend fun processUserAttachment(
        fileUri: String,
        mimeType: String,
    ): AttachmentReference {
        val base64 = Base64.encode(readFileBytes(fileUri))
        val uri = attachmentStore.saveAttachment(base64, mimeType)
        return AttachmentReference.LocalFile(uri)
    }

    override suspend fun processAssistantAttachment(
        base64: String,
        mimeType: String,
    ): AttachmentReference {
        val uri = attachmentStore.saveAttachment(base64, mimeType)
        return AttachmentReference.LocalFile(uri)
    }

    override suspend fun getAttachmentContent(
        reference: AttachmentReference,
    ): AttachmentsRepository.AttachmentContent {
        require(reference is AttachmentReference.LocalFile) {
            "Only local files are supported for now"
        }
        val base64 = attachmentStore.getAttachmentContent(reference.uri)
        return AttachmentsRepository.AttachmentContent(base64)
    }

    override suspend fun deleteAttachment(
        reference: AttachmentReference,
    ) {
        require(reference is AttachmentReference.LocalFile) {
            "Only local files are supported for now"
        }
        attachmentStore.removeAttachment(reference.uri)
    }

    private suspend fun readFileBytes(uri: String): ByteArray {
        TODO()
    }
}
