package dev.olek.lmclient.data.local.mapper

import dev.olek.lmclient.data.databases.Messages
import dev.olek.lmclient.data.models.LMClientError
import dev.olek.lmclient.data.models.Message
import dev.olek.lmclient.data.models.MessageAttachment
import dev.olek.lmclient.data.models.MessageContent
import dev.olek.lmclient.data.models.MessageFinishReason
import org.koin.core.annotation.Factory

internal typealias MessageDbModel = Messages

@Factory
internal class MessageMapper {
    fun mapToDbModel(message: Message, chatRoomId: String): MessageDbModel {
        val (finishReasonType, finishReasonMessage) = message.getFinishReasonTypeAndMessage()
        val (errorType, errorMessage) = message.toErrorTypeAndMessage()

        return MessageDbModel(
            id = message.id,
            role = message.getRole(),
            content_text = message.getContentText(),
            content_audio = null,
            content_type = message.getContentType(),
            finish_reason_type = finishReasonType,
            finish_reason_message = finishReasonMessage,
            error_type = errorType,
            error_message = errorMessage,
            token_count = null,
            chat_room_id = chatRoomId,
            created_at = "", // Will be generated by DB
        )
    }

    fun mapFromDbModel(message: MessageDbModel, attachments: List<MessageAttachment>): Message {
        val content = when (message.content_type) {
            "text" -> MessageContent.Text(message.content_text!!)
            "audio" -> MessageContent.Audio(message.content_audio!!)
            else -> error("Unknown message content type: ${message.content_type}")
        }

        return when (message.role) {
            "user" -> Message.UserMessage(
                id = message.id,
                content = content,
                attachments = attachments,
            )

            "system" -> Message.AssistantMessage(
                id = message.id,
                content = content,
                attachments = attachments,
                finishReason = message.getFinishReason(),
                error = message.getError(),
            )

            else -> error("Unknown message role: ${message.role}")
        }
    }

    fun getFinishReasonDbFormat(finishReason: MessageFinishReason?): Pair<String?, String?> = when (finishReason) {
        is MessageFinishReason.ContentFilter -> "content_filter" to null
        is MessageFinishReason.FunctionCall -> "functional_call" to null
        is MessageFinishReason.Length -> "length" to null
        is MessageFinishReason.PauseTurn -> "pause_turn" to null
        is MessageFinishReason.Stop -> "stop" to null
        is MessageFinishReason.StopSequence -> "stop_sequence" to null
        is MessageFinishReason.ToolCalls -> "tool_calls" to null
        is MessageFinishReason.Language -> "language" to null
        is MessageFinishReason.Unknown -> "unknown" to finishReason.reason
        null -> null to null
    }

    fun getErrorDbFormat(error: LMClientError?): Pair<String?, String?> = when (error) {
        is LMClientError.Authentication -> "authentication" to null
        is LMClientError.ConnectionIssue -> "connection_issue" to null
        is LMClientError.PermissionDenied -> "permission_denied" to null
        is LMClientError.RateLimit -> "rate_limit" to null
        is LMClientError.Timeout -> "timeout" to null
        is LMClientError.UnknownError -> "unknown" to error.message
        null -> null to null
    }

    private fun Message.getRole() = when (this) {
        is Message.UserMessage -> "user"
        is Message.AssistantMessage -> "system"
    }

    private fun Message.getContentText() = (this.content as? MessageContent.Text)?.text

    private fun Message.getContentType() = when (this.content) {
        is MessageContent.Audio -> "audio"
        is MessageContent.Text -> "text"
    }

    private fun Message.getFinishReasonTypeAndMessage() = when (this) {
        is Message.UserMessage -> null to null
        is Message.AssistantMessage -> when (this.finishReason) {
            is MessageFinishReason.ContentFilter -> "content_filter" to null
            is MessageFinishReason.FunctionCall -> "functional_call" to null
            is MessageFinishReason.Length -> "length" to null
            is MessageFinishReason.PauseTurn -> "pause_turn" to null
            is MessageFinishReason.Stop -> "stop" to null
            is MessageFinishReason.StopSequence -> "stop_sequence" to null
            is MessageFinishReason.ToolCalls -> "tool_calls" to null
            is MessageFinishReason.Language -> "language" to null
            is MessageFinishReason.Unknown -> "unknown" to this.finishReason.reason
            null -> null to null
        }
    }

    private fun Message.toErrorTypeAndMessage() = when (this) {
        is Message.UserMessage -> null to null
        is Message.AssistantMessage -> when (this.error) {
            is LMClientError.Authentication -> "authentication" to null
            is LMClientError.ConnectionIssue -> "connection_issue" to null
            is LMClientError.PermissionDenied -> "permission_denied" to null
            is LMClientError.RateLimit -> "rate_limit" to null
            is LMClientError.Timeout -> "timeout" to null
            is LMClientError.UnknownError -> "unknown" to this.error.message
            null -> null to null
        }
    }

    private fun MessageDbModel.getFinishReason() = when (finish_reason_type) {
        "content_filter" -> MessageFinishReason.ContentFilter
        "functional_call" -> MessageFinishReason.FunctionCall
        "length" -> MessageFinishReason.Length
        "pause_turn" -> MessageFinishReason.PauseTurn
        "stop" -> MessageFinishReason.Stop
        "stop_sequence" -> MessageFinishReason.StopSequence
        "tool_calls" -> MessageFinishReason.ToolCalls
        "language" -> MessageFinishReason.Language
        "unknown" -> MessageFinishReason.Unknown(finish_reason_message ?: "Unknown")
        null -> null
        else -> error("Unknown finish reason type: $finish_reason_type")
    }

    private fun MessageDbModel.getError() = when (error_type) {
        "authentication" -> LMClientError.Authentication
        "connection_issue" -> LMClientError.ConnectionIssue
        "permission_denied" -> LMClientError.PermissionDenied
        "rate_limit" -> LMClientError.RateLimit
        "timeout" -> LMClientError.Timeout
        "unknown" -> LMClientError.UnknownError(error_message ?: "Unknown")
        null -> null
        else -> error("Unknown error type: $error_type")
    }
}
